openapi: 3.0.0
info:
  title: psc-api-maj-v2
  version: '1.0'
  description: API CRUD for Personnels et Structures de sant√©
  contact:
    email: superviseurs.psc@esante.gouv.fr
servers:
  - url: 'http://localhost:8080/api'
    description: local api server
tags:
  - name: ps
    description: ps
  - name: structure
    description: structure
  - name: toggle
    description: toggle
paths:
  /v2/ps:
    post:
      summary: Create new Ps
      tags:
        - ps
      operationId: create-new-Ps
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Ps already exists
      description: Create a new Ps
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ps'
            examples:
              PsExample:
                value:
                  idType: '8'
                  id: '00000000001'
                  nationalId: '800000000001'
                  lastName: DUPONT
                  firstName: JIMMY
                  dateOfBirth: 17/12/1973
                  birthAddressCode: '57463'
                  birthCountryCode: '99'
                  birthAddress: METZ
                  genderCode: M
                  phone: '0601020304'
                  email: jimmy@dupont.fr
                  salutationCode: M
                  professions:
                    - exProId: 50C
                      code: '50'
                      categoryCode: C
                      salutationCode: M
                      lastName: DUPONT
                      firstName: JIMMY
                      expertises:
                        - expertiseId: SSM69
                          typeCode: S
                          code: SM69
                      workSituations:
                        - situId: SSA04
                          modeCode: S
                          activitySectorCode: SA04
                          pharmacistTableSectionCode: AC36
                          roleCode: '12'
                          structures:
                            - structureId: '1'
        description: The Ps to be created
        required: true
    put:
      summary: Update Ps
      operationId: update-ps
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Not Found
      description: Update Ps
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Ps'
            examples:
              PsExample:
                value:
                  idType: '8'
                  id: '00000000001'
                  nationalId: '800000000001'
                  lastName: DUPONT
                  firstName: JIMMY
                  dateOfBirth: 17/12/1973
                  birthAddressCode: '57463'
                  birthCountryCode: '99'
                  birthAddress: METZ
                  genderCode: M
                  phone: '0601020304'
                  email: jimmy@dupont.fr
                  salutationCode: M
                  professions:
                    - exProId: 50C
                      code: '50'
                      categoryCode: C
                      salutationCode: M
                      lastName: DUPONT
                      firstName: JIMMY
                      expertises:
                        - expertiseId: SSM69
                          typeCode: S
                          code: SM69
                      workSituations:
                        - situId: SSA04
                          modeCode: S
                          activitySectorCode: SA04
                          pharmacistTableSectionCode: AC36
                          roleCode: '12'
                          structures:
                            - structureId: '1'
        required: true
      tags:
        - ps
  '/v2/ps/{psId}':
    parameters:
      - schema:
          type: string
        name: psId
        in: path
        required: true
    get:
      summary: Get Ps by id
      tags:
        - ps
      operationId: get-ps-by-id
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ps'
              examples:
                PsExample:
                  value:
                    idType: '8'
                    id: '00000000001'
                    nationalId: '800000000001'
                    lastName: DUPONT
                    firstName: JIMMY
                    dateOfBirth: 17/12/1973
                    birthAddressCode: '57463'
                    birthCountryCode: '99'
                    birthAddress: METZ
                    genderCode: M
                    phone: '0601020304'
                    email: jimmy@dupont.fr
                    salutationCode: M
                    professions:
                      - exProId: 50C
                        code: '50'
                        categoryCode: C
                        salutationCode: M
                        lastName: DUPONT
                        firstName: JIMMY
                        expertises:
                          - expertiseId: SSM69
                            typeCode: S
                            code: SM69
                        workSituations:
                          - situId: SSA04
                            modeCode: S
                            activitySectorCode: SA04
                            pharmacistTableSectionCode: AC36
                            roleCode: '12'
                            structures:
                              - structureId: '1'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Not Found
      description: get a Ps by one of its idNationalRef
    delete:
      summary: Delete Ps by id
      tags:
        - ps
      operationId: delete-ps-by-id
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Not Found
      description: Delete a PS by its id
  '/v2/ps/force/{psId}':
    parameters:
      - schema:
          type: string
        name: psId
        in: path
        required: true
    delete:
      summary: Physical delete of Ps
      tags:
        - ps
      operationId: force-delete-ps-by-id
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Not Found
      description: completely delete Ps (not only deactivate it)
  /v2/structure:
    post:
      summary: Create new structure
      tags:
        - structure
      operationId: create-new-structure
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: Conflict
          content:
            application/json:
              schema:
                type: object
      description: Create a new structure
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Structure'
            examples:
              StructureExample:
                value:
                  siteSIRET: '12312312312345'
                  siteSIREN: '123123123'
                  siteFINESS: '260000451'
                  legalEstablishmentFINESS: '260006912'
                  structureTechnicalId: '1'
                  legalCommercialName: Structure One
                  publicCommercialName: Structure One
                  recipientAdditionalInfo: info +
                  geoLocationAdditionalInfo: geoloc info +
                  streetNumber: '1'
                  streetNumberRepetitionIndex: bis
                  streetCategoryCode: rue
                  streetLabel: de Paris
                  distributionMention: c/o M. Dupont
                  cedexOffice: '75117'
                  postalCode: '75117'
                  communeCode: '75117'
                  countryCode: FR
                  phone: '0123456789'
                  phone2: '0623456789'
                  fax: '0198765432'
                  email: structure@one.fr
                  departmentCode: '99'
                  oldStructureId: '101'
                  registrationAuthority: ARS/ARS/ARS
        required: true
    put:
      summary: Update structure
      tags:
        - structure
      operationId: update-structure
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Not Found
      description: Update structure
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Structure'
            examples:
              StructureExample:
                value:
                  siteSIRET: '12312312312345'
                  siteSIREN: '123123123'
                  siteFINESS: '260000451'
                  legalEstablishmentFINESS: '260006912'
                  structureTechnicalId: '1'
                  legalCommercialName: Structure One
                  publicCommercialName: Structure One
                  recipientAdditionalInfo: info +
                  geoLocationAdditionalInfo: geoloc info +
                  streetNumber: '1'
                  streetNumberRepetitionIndex: bis
                  streetCategoryCode: rue
                  streetLabel: de Paris
                  distributionMention: c/o M. Dupont
                  cedexOffice: '75117'
                  postalCode: '75117'
                  communeCode: '75117'
                  countryCode: FR
                  phone: '0123456789'
                  phone2: '0623456789'
                  fax: '0198765432'
                  email: structure@one.fr
                  departmentCode: '99'
                  oldStructureId: '101'
                  registrationAuthority: ARS/ARS/ARS
        required: true
  '/v2/structure/{structureId}':
    parameters:
      - schema:
          type: string
        name: structureId
        in: path
        required: true
    get:
      summary: Get structure by id
      tags:
        - structure
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Structure'
              examples:
                example-1:
                  value:
                    siteSIRET: string
                    siteSIREN: string
                    siteFINESS: string
                    legalEstablishmentFINESS: string
                    structureTechnicalId: string
                    legalCommercialName: string
                    publicCommercialName: string
                    recipientAdditionalInfo: string
                    geoLocationAdditionalInfo: string
                    streetNumber: string
                    streetNumberRepetitionIndex: string
                    streetCategoryCode: string
                    streetLabel: string
                    distributionMention: string
                    cedexOffice: string
                    postalCode: string
                    communeCode: string
                    countryCode: string
                    phone: string
                    phone2: string
                    fax: string
                    email: string
                    departmentCode: string
                    oldStructureId: string
                    registrationAuthority: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Not Found
      operationId: get-structure-by-id
      description: Get structure by id
    delete:
      summary: Delete structure by id
      tags:
        - structure
      operationId: delete-structure-by-structureId
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '410':
          description: Not Found
      description: Delete structure by structureId
  /v2/toggle:
    put:
      summary: toggle PsRef mapping
      operationId: toggle-psref
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            text/plain:
              schema:
                type: string
        '409':
          description: Conflict
          content:
            text/plain:
              schema:
                type: string
        '410':
          description: Gone
          content:
            text/plain:
              schema:
                type: string
      description: Toggle PsRef mapping
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PsRef'
            examples:
              ToggleExample:
                value:
                  nationalIdRef: '000000000001'
                  nationalId: '80000000001'
                  activated: null
                  deactivated: null
        required: true
      tags:
        - toggle
components:
  schemas:
    Expertise:
      description: Expertise
      type: object
      properties:
        expertiseId:
          type: string
        typeCode:
          type: string
        code:
          type: string
      x-examples:
        ExpertiseExample:
          expertiseId: SSM69
          typeCode: S
          code: SM69
    Structure:
      description: Structure de Sant√©
      type: object
      properties:
        siteSIRET:
          type: string
        siteSIREN:
          type: string
        siteFINESS:
          type: string
        legalEstablishmentFINESS:
          type: string
        structureTechnicalId:
          type: string
          minLength: 1
        legalCommercialName:
          type: string
        publicCommercialName:
          type: string
        recipientAdditionalInfo:
          type: string
        geoLocationAdditionalInfo:
          type: string
        streetNumber:
          type: string
        streetNumberRepetitionIndex:
          type: string
        streetCategoryCode:
          type: string
        streetLabel:
          type: string
        distributionMention:
          type: string
        cedexOffice:
          type: string
        postalCode:
          type: string
        communeCode:
          type: string
        countryCode:
          type: string
        phone:
          type: string
        phone2:
          type: string
        fax:
          type: string
        email:
          type: string
        departmentCode:
          type: string
        oldStructureId:
          type: string
        registrationAuthority:
          type: string
      required:
        - structureTechnicalId
      x-examples:
        StructureExample:
          siteSIRET: '12312312312345'
          siteSIREN: '123123123'
          siteFINESS: '260000451'
          legalEstablishmentFINESS: '260006912'
          structureTechnicalId: '1'
          legalCommercialName: Structure One
          publicCommercialName: Structure One
          recipientAdditionalInfo: info +
          geoLocationAdditionalInfo: geoloc info +
          streetNumber: '1'
          streetNumberRepetitionIndex: bis
          streetCategoryCode: rue
          streetLabel: de Paris
          distributionMention: c/o M. Dupont
          cedexOffice: '75117'
          postalCode: '75117'
          communeCode: '75117'
          countryCode: FR
          phone: '0123456789'
          phone2: '0623456789'
          fax: '0198765432'
          email: structure@one.fr
          departmentCode: '99'
          oldStructureId: '101'
          registrationAuthority: ARS/ARS/ARS
    WorkSituation:
      description: Situation d exercice
      type: object
      properties:
        situId:
          type: string
        modeCode:
          type: string
          minLength: 1
        activitySectorCode:
          type: string
        pharmacistTableSectionCode:
          type: string
        roleCode:
          type: string
        structures:
          type: array
          items:
            $ref: '#/components/schemas/StructureRef'
      x-examples:
        WorkSituationExample:
          situId: SSA04
          modeCode: S
          activitySectorCode: SA04
          pharmacistTableSectionCode: AC36
          roleCode: '12'
          structures:
            - structureId: '1'
    StructureRef:
      description: Structure reference
      type: object
      properties:
        structureId:
          type: string
      required:
        - structureId
      x-examples:
        StructureRefExample:
          structureId: '1'
    Profession:
      description: Profession
      type: object
      properties:
        exProId:
          type: string
        code:
          type: string
        categoryCode:
          type: string
        salutationCode:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        expertises:
          type: array
          items:
            $ref: '#/components/schemas/Expertise'
        workSituations:
          type: array
          items:
            $ref: '#/components/schemas/WorkSituation'
      x-examples:
        ProfessionExample:
          exProId: 50C
          code: '50'
          categoryCode: C
          salutationCode: M
          lastName: DUPONT
          firstName: JIMMY
          expertises:
            - expertiseId: SSM69
              typeCode: S
              code: SM69
          workSituations:
            - situId: SSA04
              modeCode: S
              activitySectorCode: SA04
              pharmacistTableSectionCode: AC36
              roleCode: '12'
              structures:
                - structureId: '1'
    PsRef:
      description: Mapping identifier to Ps
      type: object
      x-examples:
        PsRefExample:
          nationalIdRef: '800000000001'
          nationalId: '800000000001'
          activated: 1638791221
          deactivated: null
      properties:
        nationalIdRef:
          type: string
          minLength: 1
        nationalId:
          type: string
          minLength: 1
        activated:
          type: number
        deactivated:
          type: number
          nullable: true
      required:
        - nationalIdRef
        - nationalId
    Ps:
      description: Professionnel de sant√©
      type: object
      properties:
        idType:
          type: string
        id:
          type: string
        nationalId:
          type: string
          minLength: 1
        lastName:
          type: string
        firstName:
          type: string
        dateOfBirth:
          type: string
        birthAddressCode:
          type: string
        birthCountryCode:
          type: string
        birthAddress:
          type: string
        genderCode:
          type: string
        phone:
          type: string
        email:
          type: string
        salutationCode:
          type: string
        professions:
          type: array
          items:
            $ref: '#/components/schemas/Profession'
      required:
        - nationalId
      x-examples:
        PsExample:
          idType: '8'
          id: '00000000001'
          nationalId: '800000000001'
          lastName: DUPONT
          firstName: JIMMY
          dateOfBirth: 17/12/1973
          birthAddressCode: '57463'
          birthCountryCode: '99'
          birthAddress: METZ
          genderCode: M
          phone: '0601020304'
          email: jimmy@dupont.fr
          salutationCode: M
          professions:
            - exProId: 50C
              code: '50'
              categoryCode: C
              salutationCode: M
              lastName: DUPONT
              firstName: JIMMY
              expertises:
                - expertiseId: SSM69
                  typeCode: S
                  code: SM69
              workSituations:
                - situId: SSA04
                  modeCode: S
                  activitySectorCode: SA04
                  pharmacistTableSectionCode: AC36
                  roleCode: '12'
                  structures:
                    - structureId: '1'
    Error:
      title: Error
      type: object
      properties:
        httpStatus:
          type: number
        message:
          type: array
          items:
            type: string
      x-examples:
        ErrorExample:
          httpStatus: 500
          message:
            - MongoInterruptedException
